/**
 * Auto-generated TypeScript definitions from Zod schemas
 * @generated This file is automatically generated. Do not edit manually.
 */

type Order = {
    orderNumber: string;
    currency: string | undefined;
    coupons: CouponSummary[];
    organizerId: string;
    companyId?: string | undefined;
    version?: ("2025-04-15" | "2025-07-15" | "2025-12-15") | undefined;
    contextId: string;
    costs: OrderCosts;
    customer: Customer;
    status: "placed" | "voided" | "refunded";
    items: OrderItem[];
    answers?: {
        [key: string]: string | boolean;
    } | undefined;
    forwarded: any;
    meta: {
        resolvedContext?: ResolvedCartContext | undefined;
        priceLock?: {
            lockedAt: string;
            ttl?: number | undefined;
        } | undefined;
        [x: string]: unknown;
    };
    context?: {
        tracking?: {
            [key: string]: string;
        } | undefined;
        source?: string | undefined;
        [x: string]: unknown;
    } | undefined;
    uid: string | null;
    [x: string]: unknown;
};

type PersonAddress = {
    address_1: string;
    address_2?: string | undefined;
    city: string;
    country: string;
    premise?: string | undefined;
    formattedAddress?: string | undefined;
    localized_address_display?: string | undefined;
    localized_area_display?: string | undefined;
    localized_multi_line_address_display?: string[] | undefined;
    postal_code: string;
    region: string;
    first: string;
    last: string;
};

type OrderItemCosts = {
    cost: string;
    delivery: string;
    fee: string;
    tax: string;
    gross: string;
    total: string;
    subtotal: string;
    discount: string;
    preDiscount: string;
};

type AttendeeCosts = {
    cost: string;
    discount: string;
    gross: string;
    fee: string;
    tax: string;
    total: string;
};

type Barcode = {
    orderId: string;
    barcode: string;
    index: number;
    changed?: string | undefined;
    checkin_type?: number | undefined;
    created?: string | undefined;
    is_printed?: boolean | undefined;
    reassigned?: boolean | undefined;
    status?: string | undefined;
    uid?: string | undefined;
    offeringId: string;
    attendeeId: string;
    attendeeRefPath?: string | undefined;
    source: ("generated") | string;
    version: "2025-04-15" | "2025-07-15" | "2025-12-15";
};

type Photo = {
    "2x"?: string | undefined;
    id?: string | undefined;
    url: string;
    width?: number | undefined;
    height?: number | undefined;
    caption?: string | undefined;
    bucket?: string | undefined;
    path?: string | undefined;
};

type Location = {
    venueId: string | null;
    placeId: string | null;
    name: string;
    geometry: {
        lat: number;
        lng: number;
        zoom?: number | undefined;
        viewport?: {
            northeast: {
                lat: number;
                lng: number;
            };
            southwest: {
                lat: number;
                lng: number;
            };
        } | undefined;
        vicinity?: string | undefined;
        region?: string | undefined;
        locality?: string | undefined;
        geoHash?: string | undefined;
    } | null;
    address: {
        address_1: string;
        address_2?: string | undefined;
        city: string;
        country: string;
        premise?: string | undefined;
        formattedAddress?: string | undefined;
        localized_address_display?: string | undefined;
        localized_area_display?: string | undefined;
        localized_multi_line_address_display?: string[] | undefined;
        postal_code: string;
        region: string;
    } | null;
    timezone?: string | undefined;
};

type MultipartText = {
    /** HTML version of the content */
    html?: string | undefined;
    /** Plain text version of the content */
    text?: string | undefined;
    /** Markdown version of the content */
    md?: string | undefined;
    /** Optional rich editor blocks for structured editing */
    blocks?: (any[] | null) | undefined;
};

type Customer = {
    name: string;
    photoURL: string | null;
    /** Preferred display name for the person. Often a shortened or preferred version of their full name. */
    displayName?: (string | null) | undefined;
    first: string;
    last: string;
    gender: "male" | "female" | "other" | string | null;
    birthdate: string | null;
    age?: number | undefined;
    email: string | null;
    phone: string | null;
    uid: string | null;
    billingAddress?: (PersonAddress | null) | undefined;
    shippingAddress?: (PersonAddress | null) | undefined;
};

type CouponSummary = {
    id: string;
    code: string;
    amountOff: number;
    percentOff: number;
    offeringIds: string[];
};

type OrderCosts = {
    /** total items cost, not including tax, fee, or discount */
    subtotal: string;
    /** total fee amount */
    fee: string;
    /** total tax amount */
    tax: string;
    /** total discount amount */
    discount: string;
    /** delivery charge */
    delivery: string;
    /** cost + fee - discount, not including tax */
    gross: string;
    /** cost + fee, not including tax or discount */
    preDiscount: string;
    /** total cost including tax */
    total: string;
};

type Offering = {
    id: string;
    created: string;
    changed?: string | undefined;
    urn?: string | undefined;
    offeringGroupId?: string | undefined;
    category?: string | undefined;
    name: string;
    type: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
    capacity: number;
    quantitySold: number;
    status: "live" | "hidden" | "sold-out" | "draft" | "archived" | "deleted" | "unavailable";
    priceCategory: "donation" | "free" | "paid" | "other";
    sorting: number;
    schedule?: {
        daysOfWeek?: number[] | undefined;
        start: string;
        end: string;
        excludeDates?: string[] | undefined;
        includeDates?: string[] | undefined;
    } | undefined;
    description: string | null;
    instructions: string | null;
    step: number | undefined;
    maximumQuantity: number;
    minimumQuantity: number;
    package?: boolean | undefined;
    includes?: {
        id: string;
        quantity: number;
        type: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
        description: string | null;
        name?: string | undefined;
        refPath?: string | undefined;
    }[] | undefined;
    constraints?: any | undefined;
    hidden: boolean;
    order_confirmation_message?: (string | null) | undefined;
    costs: {
        cost: string;
        delivery: string;
        fee: string;
        tax: string;
        gross: string;
        total: string;
    };
    options?: {
        id: string;
        name: string;
        hash?: string | undefined;
        options: {
            key: string;
            description: string;
            value: string | number;
            meta?: any | undefined;
        }[];
    }[] | undefined;
    meta?: {
        [key: string]: any;
    } | undefined;
    config?: {
        groups?: {
            enabled: boolean;
            autoGenerateGroupId?: boolean | undefined;
        } | undefined;
    } | undefined;
    refPath?: string | undefined;
};

type Ticket = {
    id: string;
    created: string;
    changed?: string | undefined;
    urn?: string | undefined;
    offeringGroupId?: string | undefined;
    category: string;
    name: string;
    capacity: number;
    quantitySold: number;
    status: "live" | "hidden" | "sold-out" | "draft" | "archived" | "deleted" | "unavailable";
    priceCategory: "donation" | "free" | "paid" | "other";
    sorting: number;
    schedule?: {
        daysOfWeek?: number[] | undefined;
        start: string;
        end: string;
        excludeDates?: string[] | undefined;
        includeDates?: string[] | undefined;
    } | undefined;
    description?: string | undefined;
    instructions: string | null;
    step: number | undefined;
    maximumQuantity: number;
    minimumQuantity: number;
    package?: boolean | undefined;
    includes?: {
        id: string;
        quantity: number;
        type: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
        description: string | null;
        name?: string | undefined;
        refPath?: string | undefined;
    }[] | undefined;
    order_confirmation_message?: (string | null) | undefined;
    costs: {
        cost: string;
        delivery: string;
        fee: string;
        tax: string;
        gross: string;
        total: string;
    };
    options?: {
        id: string;
        name: string;
        hash?: string | undefined;
        options: {
            key: string;
            description: string;
            value: string | number;
            meta?: any | undefined;
        }[];
    }[] | undefined;
    meta?: {
        [key: string]: any;
    } | undefined;
    config?: {
        groups?: {
            enabled: boolean;
            autoGenerateGroupId?: boolean | undefined;
        } | undefined;
    } | undefined;
    refPath?: string | undefined;
    type: "admission" | "package" | "admission.tableCommitment";
    source: string;
    display_name?: string | undefined;
    ticketParentId?: string | undefined;
    salesEnd: string;
    salesStart: string;
    parentId?: string | undefined;
    refId?: string | undefined;
};

type Event = {
    id: string;
    created: string;
    changed: string;
    version: "2025-04-15" | "2025-07-15" | "2025-12-15";
    name: string;
    summary: string;
    companyId: string;
    tz: string;
    start: string;
    end: string;
    isSeries: boolean;
    status: "archived" | "queued" | "draft" | "live" | "started" | "ended" | "completed" | "canceled";
    flyer: (Photo | null) | undefined;
    currency: string;
    public: boolean;
    location?: Location | undefined;
    organizerId: string;
    appId: string;
    refId?: string | undefined;
    locale: string;
    capacity: number;
    description?: MultipartText | undefined;
    settings?: {
        scanningContextId?: string | undefined;
    } | undefined;
    stats?: any | undefined;
    config?: any | undefined;
    appearance: any | undefined;
    source?: string | undefined;
    channels: string[];
    sections: string[] | undefined;
    seriesParentId?: string | undefined;
    venueId?: string | undefined;
    meta?: any | undefined;
    slug?: string | undefined;
    ticketPrices?: string[] | undefined;
    ticketGroups?: {
        id: string;
        sorting: number;
        name: string;
        description?: (string | null) | undefined;
        status: "live" | "sold-out" | "hidden";
    }[] | undefined;
    tags: string[];
    searchTags: string[];
    pageId: string | null;
    clonedFromId?: string | undefined;
};

type EventProfile = {
    id: string;
    created: string;
    changed: string;
    version: "2025-04-15" | "2025-07-15" | "2025-12-15";
    name: string;
    summary: string;
    companyId: string;
    tz: string;
    start: string;
    end: string;
    isSeries: boolean;
    status: "archived" | "queued" | "draft" | "live" | "started" | "ended" | "completed" | "canceled";
    flyer: (Photo | null) | undefined;
    currency: string;
    public: boolean;
    location?: Location | undefined;
    organizerId: string;
    meta?: any | undefined;
    organizer: {
        /** Unique identifier for the organizer */
        id: string;
        /** URL-friendly slug for the organizer profile */
        slug?: string | undefined;
        /** ID of the company this organizer belongs to */
        companyId: string;
        /** Short biography or description of the organizer */
        bio?: string | undefined;
        /** Detailed description in multiple formats */
        description?: MultipartText | undefined;
        /** Brief summary in multiple formats */
        summary?: MultipartText | undefined;
        /** Number of followers */
        followers: number;
        /** Headline or tagline for the organizer */
        headline?: string | undefined;
        /** Logo photo with multiple resolutions */
        logo?: Photo | undefined;
        /** Display name of the organizer */
        name: string;
        /** Social media links mapped by platform */
        links: {
            /** Social media platform/category (e.g., facebook, twitter) */
            category: ("facebook" | "twitter" | "instagram" | "linkedin" | "youtube" | "tiktok" | "website") | string;
            /** URL to the social media profile or page */
            url: string;
            /** Priority for ordering links */
            priority: number;
            /** Indicates if this is the primary link */
            isPrimary: boolean;
        }[];
        /** Custom appearance configuration for branding */
        appearance?: ({
            id: string;
            css?: string | undefined;
            fontFamily?: string | undefined;
            fontSizeBase?: string | undefined;
            palleteDefaultMode: ("light" | "dark" | "auto") | undefined;
            pallete?: Record<"light" | "dark" | "auto", {
                    colorBackground?: string | undefined;
                    colorSurface?: string | undefined;
                }> | undefined;
        } | null) | undefined;
        /** Additional configuration data */
        config?: any | undefined;
        /** Organizer-specific settings */
        settings?: {
            /** Asset ID for confirmation emails or pages */
            confirmationAssetId?: string | undefined;
        } | undefined;
    } | null;
    url?: string | undefined;
    slug: string;
    channels: string[];
    description: MultipartText;
    ticketPrices: string[];
    venue?: any | undefined;
    tags: string[];
    searchTags: string[];
    sections: string[];
    priceOptions?: string[] | undefined;
    grossPriceOptions?: string[] | undefined;
    priceRange?: {
        min?: string | undefined;
        max?: string | undefined;
    } | undefined;
};

type OfferingSnapshot = {
    id: string;
    refPath?: string | undefined;
    urn?: string | undefined;
    category?: string | undefined;
    description: string | null;
    name: string;
    type: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
    includes?: {
        id: string;
        quantity: number;
        type: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
        description: string | null;
        name?: string | undefined;
        refPath?: string | undefined;
    }[] | undefined;
    meta?: {
        [key: string]: any;
    } | undefined;
    costs?: {
        cost: string;
        delivery: string;
        fee: string;
        tax: string;
        gross: string;
        total: string;
    } | undefined;
    sorting: number | undefined;
    config?: {
        groups?: {
            enabled: boolean;
            autoGenerateGroupId?: boolean | undefined;
        } | undefined;
    } | undefined;
};

type ResolvedCartContext = {
    id: string;
    title: string;
    location?: Location | undefined;
    logo?: Photo | undefined;
    start: string;
    end?: string | undefined;
    offerings: {
        [key: string]: {
            path: string;
            offering: Offering;
        };
    };
    config: any;
};

type OrderItem = {
    id: string;
    purchaseGroupId: string | null;
    tableCommitment?: {
        id: string;
        groupSize: number;
        ticketsPurchased: number;
        completed: boolean;
    } | undefined;
    offeringType: "admission" | "admission.tableCommitment" | "package" | "skip" | "drink" | "ticket" | "tc-ticket" | "merch" | "donation" | "membership" | "voucher" | "service" | "other";
    offeringId: string;
    quantity: number;
    costs: OrderItemCosts;
    includedWithItemId: string | null;
    details: string | null;
    options: any | null;
    offering: OfferingSnapshot;
};

type Attendee = {
    id: string;
    created: string;
    changed: string;
    version: "2025-04-15" | "2025-07-15" | "2025-12-15";
    orderId: string;
    offeringId: string;
    orderNumber: string;
    uid: string | null;
    profile: Customer | null;
    checkedIn: boolean;
    barcodes: string[];
    status: ("attending" | "checkedIn" | "cancelled" | "refunded" | "noShow" | "unknown") | string;
    orderItemId: string;
    index: number;
    source: ("imported" | "online" | "offline" | "onsite") | string;
};

// Pagination types
type Pagination = {
    size: number;
    page: number;
    continuation?: string | undefined;
};

type PaginationResponse = Pagination & {
    total: number;
};

type PaginatedResponse<T> = {
    results: T[];
    pagination: PaginationResponse;
};

type PaginatedRequest<T> = T & {
    pagination?: Pagination | undefined;
};

// Cart session types
type CartSessionItemOffering = OfferingSnapshot & {
    options?: Offering['options'];
    maximumQuantity: number;
    minimumQuantity: number;
    status: Offering['status'];
    includes?: Offering['includes'];
};

type CartSessionItem = {
    id: string;
    details: string | null;
    offeringId: string;
    quantity: number;
    options: any | null;
    purchaseGroupId: string | null;
    costs?: OrderItemCosts | undefined;
    offering: CartSessionItemOffering;
};

type CartSession = {
    id: string;
    created: string;
    changed?: string | undefined;
    currency: string | undefined;
    contextId: string;
    version?: ("2025-04-15" | "2025-07-15" | "2025-12-15") | undefined;
    coupons?: CouponSummary[] | undefined;
    companyId?: string | undefined;
    organizerId: string;
    orderId?: string | undefined;
    orderNumber?: string | undefined;
    uid: string | null;
    customer?: Partial<Customer> | undefined;
    context: {
        ipAddresses?: string[] | undefined;
        userAgent?: string | undefined;
        referrer?: string | undefined;
        uid?: string | null | undefined;
        cartSessionId?: string | undefined;
        originDomain?: string | undefined;
        tracking?: Record<string, string> | undefined;
        forward?: Record<string, any> | undefined;
    };
    items: CartSessionItem[];
    costs?: {
        subtotal: string;
        discount: string;
        tax: string;
        fee: string;
        delivery: string;
        total: string;
    } | undefined;
    paymentStatus: "pending" | "confirmed" | "failed" | "refunded";
    paymentIntentId?: string | undefined;
    paymentIntentClientSecret?: string | undefined;
    forwarded?: any | undefined;
    customerAnswers?: any | undefined;
    status: "started" | "completed" | "stale" | "abandoned" | "cancelled";
    meta: {
        stale: { hard: number; soft: number; idle: number };
        resolvedContext?: ResolvedCartContext | undefined;
        [key: string]: any;
    };
};

type StartCartSessionInput = {
    contextId: string;
    sessionContext?: {
        userAgent?: string | undefined;
        referrer?: string | undefined;
        originDomain?: string | undefined;
        tracking?: Record<string, string> | undefined;
        forward?: Record<string, any> | undefined;
    } | undefined;
};

type UpdatableCartSession = {
    customer?: Partial<Customer> | undefined;
    items?: CartSessionItem[] | undefined;
    customerAnswers?: any | undefined;
    forwarded?: any | undefined;
};

// Exports
export type { Order, PersonAddress, OrderItemCosts, AttendeeCosts, Barcode, Photo, Location, MultipartText, Customer, CouponSummary, OrderCosts, Offering, Ticket, Event, EventProfile, OfferingSnapshot, ResolvedCartContext, OrderItem, Attendee, Pagination, PaginationResponse, PaginatedResponse, PaginatedRequest, CartSession, CartSessionItem, CartSessionItemOffering, StartCartSessionInput, UpdatableCartSession };
